name: build and run corpus through fuzzers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: install packages
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 8
        sudo ./llvm.sh 9
    - uses: actions/checkout@v1
      with:
        ref: paul/fuzz_experiment      
    - name: build
      run: ./build_like_ossfuzz.sh
  buildcorpus:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10
    env:
      fuzzer: parser
    steps:
      - name: run the fuzzer $fuzzer
        run: |
          mkdir -p out/$fuzzer
          build-ossfuzz-fast8/fuzz/fuzz_$fuzzer out/$fuzzer -max_total_time=20
        
