name: build and run corpus through fuzzers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      fuzzer: parser
    steps:
    - name: install packages
      run: |
        sudo apt install ninja-build
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 8
    - uses: actions/checkout@v1
      with:
        ref: paul/fuzz_experiment      
    - name: list clang versions
      run: |
        ls /usr/bin/clang*
        which clang++
        clang++ --version
    - name: build all variants
      run: ./build_like_ossfuzz.sh      
    - name: run the fuzzer $fuzzer
      run: |
        mkdir -p out/$fuzzer
        build-ossfuzz-fast8/fuzz/fuzz_$fuzzer out/$fuzzer -max_total_time=20
        
